"""add indexes for hot-path queries

Revision ID: 3c1ca782d6ba
Revises: e8282f6af748
Create Date: 2026-05-04 19:33:19.631993+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c1ca782d6ba'
down_revision: Union[str, None] = 'e8282f6af748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainingdaycompletion', schema=None) as batch_op:
        batch_op.create_index('ix_traincomp_athlete_sheet_day', ['athlete_id', 'training_sheet_id', 'week_number', 'day', 'date_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainingdaycompletion_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainingdaycompletion_date_completed'), ['date_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainingdaycompletion_training_sheet_id'), ['training_sheet_id'], unique=False)

    with op.batch_alter_table('trainingsetexecution', schema=None) as batch_op:
        batch_op.create_index('ix_setexec_athlete_sheet_day', ['athlete_id', 'training_sheet_id', 'week_number', 'day', 'date_completed'], unique=False)
        batch_op.create_index('ix_setexec_sheet_date', ['training_sheet_id', 'date_completed', 'week_number'], unique=False)

    with op.batch_alter_table('trainingsheet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainingsheet_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainingsheet_coach_id'), ['coach_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainingsheet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainingsheet_coach_id'))
        batch_op.drop_index(batch_op.f('ix_trainingsheet_athlete_id'))

    with op.batch_alter_table('trainingsetexecution', schema=None) as batch_op:
        batch_op.drop_index('ix_setexec_sheet_date')
        batch_op.drop_index('ix_setexec_athlete_sheet_day')

    with op.batch_alter_table('trainingdaycompletion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainingdaycompletion_training_sheet_id'))
        batch_op.drop_index(batch_op.f('ix_trainingdaycompletion_date_completed'))
        batch_op.drop_index(batch_op.f('ix_trainingdaycompletion_athlete_id'))
        batch_op.drop_index('ix_traincomp_athlete_sheet_day')

    # ### end Alembic commands ###
